version: "3"

services:

  php:
    image: skilldlabs/${PHP_IMAGE} # Allowed: 7.1, 5.6.
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/html:z
    networks:
      - front

  nginx:
    image: skilldlabs/${WEB_SERVER_IMAGE}
    container_name: "${COMPOSE_PROJECT_NAME}_web"
    links:
      - php:php
    depends_on:
      - php
    volumes:
      - ../:/var/www/html:z
      - ./nginx/drupal8.conf:/etc/nginx/conf.d/drupal8.conf:z
    restart: always
    networks:
      - front

  mysql:
    image: ${DB_IMAGE}
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - front

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${IPRANGE}"
