info_currency.settings:
  type: config_object
  label: 'Default currency settings'
  mapping:
    base_currency:
      type: string
      label: 'Site base currency'
    currency_update_interval:
      type: integer
      label: 'Currency update interval'
